import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="min-h-[50vh]">{children}</main>
        <Toaster position="top-right" />
        <Footer />
      </body>
    </html>
  );
}
